name: chat
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.9.0
  cloud_firestore: ^5.6.0
  firebase_messaging: ^15.2.0
  firebase_auth: ^5.3.4
  uuid: ^4.5.1
  fluttertoast: ^8.2.10
  intl: ^0.19.0
  flutter_contacts: ^1.1.7+1
  image_picker: ^1.1.2
  file_picker: ^8.1.7
  video_player: ^2.8.2
  permission_handler: ^11.3.1

  firebase_storage: ^12.3.7
  flutter_pin_code_fields: ^2.1.0
  country_picker: ^2.0.20
  cached_network_image: ^3.3.1
  country_pickers: ^3.0.1
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^8.0.3
  font_awesome_flutter: ^10.8.0
  get_time_ago: ^2.1.1
  swipe_to: ^1.0.2
  emoji_picker_flutter: ^4.2.0

  giphy_picker: ^3.0.1
  flutter_sound: ^9.2.13
  path_provider: ^2.0.14
  audioplayers: ^6.1.0
  just_audio: ^0.9.32
  flutter_story_view: 0.0.4
  cupertino_icons: ^1.0.6
  timeago: ^3.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
